### ISSUE TITLE
Bug for deserialising fields of type Optional[Dataclass]

### ISSUE THREAD

**Issue by FilipDeleersnijder** [madman-bob/python-dataclasses-serialization#3] opened 2019-09-12 11:58 UTC
Whenever you want to serialise/deserialise a dataclass that has as one of its field an Optional[T] with T being another dataclass, deserialising fails.

Code to reproduce: 

```
from typing import Optional
from unittest import TestCase

from dataclasses import dataclass
from dataclasses_serialization.json import JSONSerializer

class TestDeleteme(TestCase):

    def test_one(self):

        dc1 = DC1()
        dc2 = DC2()

        JSONSerializer.deserialize(DC1, JSONSerializer.serialize(dc1))
        serialised_value = JSONSerializer.serialize(dc2)
        JSONSerializer.deserialize(DC2, serialised_value)

@dataclass
class DC1:
    value: Optional[float] = None

@dataclass
class DC2:
    optional_dc1: Optional[DC1] = None

```

**Comment by madman-bob** [comment] 2019-09-14 13:13
The problem is not just for `Optional`, but also all `Union`s involving dataclasses.

Fixed in 8217789b15aac593be139cada7bd7badc937a9b0, and released as 1.2.2.

**Closed by madman-bob** 2019-09-14 13:13 UTC
