### ISSUE TITLE
default none values throws an exception

### ISSUE THREAD

**Issue by DanielleFundbox** [madman-bob/python-dataclasses-serialization#10] opened 2020-05-13 06:05 UTC
```@dataclass
class InfoWithNone:
    status: str
    product_types: List[str]
    id: int = None

info = InfoWithNone(status='active', product_types=['p1','p2'])
serialized_info = JSONSerializer.serialize(info)
deserialized_info = JSONSerializer.deserialize(InfoWithNone, serialized_info)

this throws
dataclasses_serialization.serializer_base.DeserializationError: Missing one or more required fields to deserialize
 {'status': 'active', 'product_types': ['p1', 'p2'], 'id': None} as <class 'tests.test_dataclasses_serialization.InfoWithNone'>
```

**Comment by DanielleFundbox** [comment] 2020-05-13 06:05
original exception is 
```dataclasses_serialization.serializer_base.DeserializationError: Cannot deserialize <class 'NoneType'> None to type <class 'int'>```

**Comment by madman-bob** [comment] 2020-05-13 09:20
Duplicate of https://github.com/madman-bob/python-dataclasses-serialization/issues/5.

`None` is not of type `int`, so it rightfully throws an error.

You want `Optional[int]`.

**Closed by madman-bob** 2020-05-13 09:20 UTC
